On 7 paid manager
thanhvan181/OnlineWorkingSystem pull request #9
Opened 2022-08-28 10:09 UTC by thanhvan181

2022-08-28 13:35 UTC, HiamQuan approved these changes

2022-08-28 13:38 UTC, HiamQuan requested changes
Sửa hết các saleman thành paidManager

2022-08-28 16:17 UTC, vanchuongkieu reviewed
Kiểm tra lại @thanhvan181

2022-09-02 15:08 UTC, vanchuongkieu approved these changes

2022-09-06 07:09 UTC, HiamQuan requested changes

2022-09-06 07:09 UTC, HiamQuan commented on src/api/v1/controllers/paidmanager.controller.js
> +    const saleman = await paidmanagerService.create(req.body);
saleman => paidmanager

2022-09-06 07:09 UTC, HiamQuan commented on src/api/v1/controllers/paidmanager.controller.js
> +    const salemans = await paidmanagerService.getAll();
Gọi hàm từ bên service chưa đúng tên hàm
getAll() => findAll()
...

2022-09-06 13:53 UTC, vanchuongkieu approved these changes

2022-09-10 17:10 UTC, HiamQuan approved these changes

2022-09-10 17:11 UTC, merged